<?php
/**
 * 公用常量定义文件
 * @author gary (yanggaojiao@qq.com)
 * @date 2014-11-30 
 */

//环境
defined('ENVIRONMENT') || define('ENVIRONMENT', 'production');

define('ICONV_FROM', 'UTF-8');
define('ICONV_TO', 'gb2312');

//日志类型
define('ROLL_FILE_LOGGER', 1);
define('DATE_FILE_LOGGER', 2);
define('DIRECT_ECHO', 3);
define('DEFAULT_LOG_MAX_SIZE', 1024 * 1024 * 10);
define('DEFALUT_LOG_SAVE_NUM', 5);

//日志级别
define('LP_BASE', 1);
define('LP_TRACE', LP_BASE << 1);
define('LP_DEBUG', LP_BASE << 2);
define('LP_INFO', LP_BASE << 3);
define('LP_USER1', LP_BASE << 4);
define('LP_USER2', LP_BASE << 5);
define('LP_WARNING', LP_BASE << 6);
define('LP_ERROR', LP_BASE << 7);
define('LP_CRITICAL', LP_BASE << 8);
define('LP_MAX', LP_CRITICAL);

// Validator常量定义
define('VALIDATE_ERROR_BASE', -1000);
define('VALIDATE_ERROR_EXIST', VALIDATE_ERROR_BASE - 1);
define('VALIDATE_ERROR_MIN', VALIDATE_ERROR_BASE - 2);
define('VALIDATE_ERROR_MAX', VALIDATE_ERROR_BASE - 3);
define('VALIDATE_ERROR_MINLEN', VALIDATE_ERROR_BASE - 4);
define('VALIDATE_ERROR_MAXLEN', VALIDATE_ERROR_BASE - 5);
define('VALIDATE_ERROR_WRONG_FORMAT', VALIDATE_ERROR_BASE - 6);
define('VALIDATE_ERROR_INCLUDE_VALUE', VALIDATE_ERROR_BASE - 7);
define('VALIDATE_ERROR_EXCLUDE_VALUE', VALIDATE_ERROR_BASE - 8);
define('VALIDATE_ERROR_CUSTOM', VALIDATE_ERROR_BASE - 9);

define('VALIDATE_DATATYPE_BASE', 1000);
define('VALIDATE_DATATYPE_INT', VALIDATE_DATATYPE_BASE + 1);
define('VALIDATE_DATATYPE_STRING', VALIDATE_DATATYPE_BASE + 2);
define('VALIDATE_DATATYPE_UIN', VALIDATE_DATATYPE_BASE + 3);
define('VALIDATE_DATATYPE_EMAIL', VALIDATE_DATATYPE_BASE + 4);
define('VALIDATE_DATATYPE_URL', VALIDATE_DATATYPE_BASE + 5);
define('VALIDATE_DATATYPE_TEL', VALIDATE_DATATYPE_BASE + 6);
define('VALIDATE_DATATYPE_MOBILE', VALIDATE_DATATYPE_BASE + 7);
define('VALIDATE_DATATYPE_ZIPCODE', VALIDATE_DATATYPE_BASE + 8);
define('VALIDATE_DATATYPE_NUMBER', VALIDATE_DATATYPE_BASE + 9);
define('VALIDATE_DATATYPE_DATETIME', VALIDATE_DATATYPE_BASE + 10);
define('VALIDATE_DATATYPE_CUSTOM', VALIDATE_DATATYPE_BASE + 11);
define('VALIDATE_DATATYPE_CUSTOM_BASE', VALIDATE_DATATYPE_BASE + 12);
?>
